# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PyBoard', '0002_auto_20160505_0521'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topics',
            new_name='Topic',
        ),
    ]
