# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 05:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PyBoard', '0003_auto_20160505_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='register_datetime',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 5, 5, 49, 35, 710708, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='register_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 5, 5, 49, 51, 112279, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='update_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topicdetail',
            name='register_datetime',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 5, 5, 50, 2, 239815, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topicdetail',
            name='register_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topicdetail',
            name='topic_no',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='PyBoard.Topic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topicdetail',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 5, 5, 50, 50, 791671, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topicdetail',
            name='update_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
