# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyBoard', '0005_auto_20160505_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicdetail',
            old_name='topic_no',
            new_name='topic',
        ),
        migrations.AddField(
            model_name='topicdetail',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
