# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PyBoard', '0006_auto_20160505_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicdetail',
            old_name='topic',
            new_name='title',
        ),
    ]
