# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyBoard', '0007_auto_20160507_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='register_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='topic',
            name='update_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='topicdetail',
            name='register_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='topicdetail',
            name='update_name',
            field=models.CharField(max_length=30),
        ),
    ]
